kind: pipeline
type: kubernetes
name: default

steps:
- name: AO Coverage Verify
  image: node:lts
  environment:
    FORMAT: cobertura
    REPORT_FILE: coverage/cobertura-coverage.xml
    HOST_DIR: /dist
    VERBOSE: true
    COV_TOKEN:
      from_secret: token
  commands:
  - mkdir -p $HOST_DIR && chown $USER:$USER $HOST_DIR
  - yarn install --immutable --immutable-cache --check-cache
  - yarn run lint
  - yarn run test:coverage
  - curl --proto '=https' --tlsv1.2 -sSf https://cov.submelon.dev/sh | sh

trigger:
  branch:
  - trunk
  event:
  - pull_request
  - push
  - custom