kind: pipeline
type: kubernetes
name: default

steps:
- name: AO Coverage Verify
  image: node:lts
  environment:
    FORMAT: cobertura
    REPORT_FILE: coverage/cobertura-coverage.xml
    HOST_DIR: /dist
    VERBOSE: "true"
    COV_TOKEN:
      from_secret: token
  commands:
  - mkdir -p $HOST_DIR && chown $USER:$USER $HOST_DIR
  - yarn install --immutable --immutable-cache --check-cache
  - yarn run lint
  - yarn run test:coverage
  - curl --proto '=https' --tlsv1.2 -sSf https://cov.submelon.dev/sh | sh
- name: publish
  image: plugins/docker
  settings:
    repo: "${DRONE_REPO}"
    tags:
      - "${DRONE_COMMIT_SHA}"
      - latest
    target: release
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      exclude:
      - tag
- name: publish
  image: plugins/docker
  settings:
    repo: "${DRONE_REPO}"
    tags:
      - "${DRONE_COMMIT_SHA}"
      - "${DRONE_TAG}"
      - latest
    target: release
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      include:
      - tag
- name: deploy
  image: quay.io/honestbee/drone-kubernetes 
  environment:
    KUBE_SERVER:
      from_secret: kube_server
    KUBE_TOKEN:
      from_secret: kube_token
  settings:
    kubernetes_server: "${KUBE_SERVER}"
    kubernetes_token: "${KUBE_TOKEN}"
    namespace: default
    deployment: gitcov-deployment
    repo: "${DRONE_REPO}"
    container: gitcov-container
    tag: "${DRONE_COMMIT_SHA}"

trigger:
  branch:
  - trunk
  event:
  - pull_request
  - push
  - custom
  - tag