kind: pipeline
type: kubernetes
name: default

steps:
- name: AO Coverage Verify
  image: node:lts
  commands:
  - mkdir -p /dist && chown $USER:$USER /dist && cp .env.sample .env
  - yarn install --immutable --immutable-cache --check-cache
  - yarn run test:coverage
  - curl --proto '=https' --tlsv1.2 -sSf https://cov.submelon.dev/sh | sh

trigger:
  branch:
  - trunk
  event:
  - pull_request
  - push
  - custom