version: '3.8'

services:
  aocov:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-buster
        MONGO_TOOLS_VERSION: "5.0"

        # Volume directory for hosted files. This directory is created on image build with proper permissions. This is set as an env-var in the Dockerfile
        HOST_DIR: /dist

    environment:
      # port and bind info
      PORT: 3000
      BIND_ADDRESS: localhost
      TARGET_URL: http://localhost:3000

      # DB info
      MONGO_URI: mongodb://aocov-db:27017
      MONGO_DB: ao-coverage

      # App configuration
      LOG_LEVEL: info
      UPLOAD_LIMIT: 4194304
      STAGE_1: 95
      STAGE_2: 80

    volumes:
      - ..:/workspace:cached
      - dev-dist:/dist:cached

    command: sleep infinity
    network_mode: service:aocov-db
    user: node

  aocov-db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d

    environment:
      MONGO_INITDB_DATABASE: ao-coverage

volumes:
  mongodb-data:
  node-nm:
  dev-dist: